### ISSUE TITLE
Eventbrite

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fableconf#14]
I have published the event in Eventbrite, please have a look and tell me if something needs to be corrected before announcing it. A few things like the start and end times may still change a bit.

https://www.eventbrite.com/e/fableconf-bordeaux-tickets-34089709238

**Comment by whitetigle** [comment]
Ok. Seems good to me 👍 !

**Comment by forki** [comment]
Awesome

Am 27.04.2017 7:51 vorm. schrieb "Whitetigle" <notifications@github.com>:

**Comment by forki** [comment]
can we have the fable logo on the eventbrite site?

**Comment by forki** [comment]
it's a mix of spanish (??) eventbrite settings and english text. Maybe change it to english settings.

**Comment by forki** [comment]
can someone photoshop the fable logo into the building? ;-)

**Comment by forki** [comment]
the price is 77,06€ that's a bit weird. Can you make it 80?

**Comment by alfonsogarciacaro** [comment]
I've updated the page, can you please check?

- Seems Eventbrite automatically chose Spanish settings (I thought they were set for each user), I changed that.
- The price is actually 60€ + taxes and fees. I changed it to 80€ including everything.
- I've added a question for Meal preference (just Vegetarian), it appears only in the checkout.

About the logo, I was thinking if we should create a new logo for the conference (and I also need to publish the website), but that's another story.

**Comment by forki** [comment]
* price: ok
* english: ok
* logo: don't make it too complicated. fable logo would be fine.

**Comment by forki** [comment]
Ok I bought a ticket. Process works. But somehow between checkout in went Spanish on me. Nothing really important I think. Just weird

**Comment by alfonsogarciacaro** [comment]
@forki You didn't have to buy the ticket ;) I'm not sure about the Spanish thing, maybe it's because the tickets are billed to a Spanish company or just some cache from previous settings /shrug.

**Comment by forki** [comment]
It's fine. That money is going to good cause. Also so I'm checking from
user perspective if everything works.

Am 27.04.2017 10:18 nachm. schrieb "Alfonso Garcia-Caro" <
notifications@github.com>:

@forki <https://github.com/forki> You didn't have to buy the ticket ;) I'm
not sure about the Spanish thing, maybe it's because the tickets are billed
to a Spanish company or just some cache from previous settings /shrug.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/fable-compiler/fableconf/issues/14#issuecomment-297827581>,
or mute the thread
