### ISSUE TITLE
Speaker Hotel / Compensation

### ISSUE THREAD

**Issue by rommsen** [fable-compiler/fableconf#55]
Hi there,
I am currently planning my travels an I wanted to ask if there is a designated speaker hotel in which we all should book our stay. In my experience it is much nicer, when all the people share a hotel and are not scattered around the city (especially in a big city like Berlin).

On this regard I also wanted to know if there are any plans to compensate for travel/accomodations?

Regards,

Roman

**Comment by alfonsogarciacaro** [comment]
We're planning to help speakers with travel cost but unfortunately we cannot give a exact amount yet because this depends on how many tickets (please help us promote the event!) and how much funding we can get from sponsors. We're working on this at the moment. Because of this and because the time we have available for organization is limited, we haven't been able to find a hotel for everybody so for now speakers are arranging their own lodging, sorry for that! But if you need any help please contact us via Twitter DM and we'll try to help as much as we can.

**Comment by rommsen** [comment]
Ok. No problems. Then I will take care of this stuff myself.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime @evelinag @selketjah @vbfox @theimowski @Zaid-Ajaj @Krzysztof-Cieslak @jfellien @Dzoukr @rommsen @tpetricek @bruinbrown @StachuDotNet @dbrattli @dersia @fergusmeiklejohn

Hi everybody! Again thanks a lot for making FableConf/Remmidemmi possible! We should be receiving the money from the ticket sales in the coming days and we're expecting to have some budget left to help you with the travel costs :+1:

If you want a reimbursement, could you please send me an email to alfonso.garcia-caro (at) outlook.com with the amount of your flight/train and hotel bill?

Thank you!

**Comment by isaacabraham** [comment]
Also please provide @alfonsogarciacaro with receipts for the expenses.
